arch: s390x
services:
  - docker
script: docker login quay.io -u $ROBOT_USER -p $ROBOT_TOKEN && docker build . --tag quay.io/zacburns/multiarch-example && docker push quay.io/zacburns/multiarch-example
