arch: s390x
services:
  - docker
before_script: 
  - if [ "$TEST_SCRIPT" ]; then cd $TEST_DIR && chmod +x $TEST_SCRIPT; fi
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
  - if [ "$TEST_SCRIPT" ]; then cd $TEST_DIR && bash $TEST_SCRIPT; fi 
